### PR TITLE
Backend refactor

### PR DESCRIPTION
**Pull request by caelchristian**

### CODE REVIEW

**Comment by caelchristian** [comment]
don't actually merge this yet, can't get docker to build

**Comment by qwarden** [comment]
@caelchristian This is more personal preference on my part but I think that we don't really need to split up the code like this at this point. All of this stuff could be accomplished with a global database object and a single package. I'm not sure that we really need the server struct at this point since all the all of the server state can be handled in the main function at the moment. I can see a future where it might be good to encapsulate that stuff but for now, I think the code could have the same functionality without as much complexity. If you think that this is the right approach and feel like we will need these features right now that is fine too. My preference would be to go back to the structure that we had before your refactor but with your model and controller changes.

**Comment by qwarden** [comment]
@caelchristian Will you take a look at this before I approve it and merge it in.

**Comment by caelchristian** [comment]
@qwarden Great work! I think this is way cleaner. Looks merge-ready to me.

**Comment by qwarden** [comment]
@caelchristian Great! I'll merge and then I am going to work on a simple login endpoint which I think we need to start making requests from the frontend.

**Review by qwarden — APPROVED** [review]

**Pull request merged**
